version: "3.8"
services:
  store_backend:
    container_name: store_backend
    image: postgres
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=store_database
      - PGHOST=store_db # NAME OF THE SERVICE
    depends_on:
      - store_db
  store_db:
    container_name: store_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store_database
    volumes:
      - store_data:/var/lib/postgresql/data
volumes:
  store_data: {}
